"""Local-source grounded defaults for a fresh portfolio install."""
backend_skills = ["Python", "Django", "Django REST Framework", "HTML", "CSS", "JavaScript", "PostgreSQL", "SQLite", "Git", "GitHub"]
fallback_projects = [
 {"slug":"talentbridge","name":"TalentBridge","category":"Recruitment platform","short_desc":"Django REST backend for candidate and vacancy workflows.","description":"A Django REST API covering candidates, employers, vacancies, shortlisting, interviews, milestones, notifications, audit events, and reports.","technical_notes":["Django REST Framework","PostgreSQL or SQLite","Redis and Celery","OpenAPI with drf-spectacular"],"tags":["Python","Django","DRF","PostgreSQL"],"visual_label":"Candidate and vacancy workflow"},
 {"slug":"smart-document-vault","name":"Smart Document Vault","category":"Document management SaaS","short_desc":"Multi-tenant document-management API with workspace isolation.","description":"A Django REST API for personal, family, and small-business document storage, organized around workspace tenancy and private-by-default documents.","technical_notes":["Django REST Framework","Workspace-scoped queries","JWT authentication","Versioned files and scan status"],"tags":["Python","Django","DRF","Multi-tenancy"],"visual_label":"Private workspace document vault"},
 {"slug":"hotelmotel","name":"HotelMotel","category":"Hotel operations","short_desc":"Django API foundation for hotels, rooms, guests, and bookings.","description":"A Django backend organized into hotel, room, guest, booking, housekeeping, billing, and access-control applications.","technical_notes":["Django REST API","Booking and stay records","Room and hotel services","Role and permission models"],"tags":["Python","Django","Bookings","RBAC"],"visual_label":"Hotel booking operations"},
 {"slug":"portfolio-website","name":"Portfolio Website","category":"Personal site","short_desc":"Django portfolio site for projects, experience, and contact.","description":"A Django-powered personal portfolio with database-backed profile content, projects, experience, and a contact form.","technical_notes":["Django class-based views","Database-backed content","Contact form persistence"],"tags":["Python","Django","HTML","CSS"],"visual_label":"Developer portfolio"},
 {"slug":"theproperty","name":"TheProperty","category":"Real estate marketplace","short_desc":"Role-aware Django marketplace for reviewed property listings in Bangladesh.","description":"A server-rendered real-estate marketplace connecting buyers, sellers, agents, and staff through controlled listing, discovery, and inquiry workflows.","technical_notes":["Django 5.2 LTS and PostgreSQL","Buyer, seller, agent, and staff workspaces","Moderated property publication lifecycle","Private identity-document storage","Redis rate limits and production operations"],"tags":["Python","Django","PostgreSQL","RBAC"],"visual_label":"Bangladesh property marketplace"},
]
fallback_experiences = [{"designation":"Backend Developer","company":"Wege LLC","period":"September 2023 - June 2024","address":"Ajman, UAE"},{"designation":"Django Developer","company":"Meektec IT","period":"Apr 2022 – Jan 2023","address":"Cumilla, Bangladesh"},{"designation":"Web Developer","company":"Research Rider","period":"Dec 2021 – Mar 2022","address":"Dhaka, Bangladesh"}]

from .case_study_content import CASE_STUDIES
for project in fallback_projects:
    project.update(CASE_STUDIES.get(project["name"], {}))
