"""Curated screenshots and montages supplied for the portfolio."""

PROJECT_SHOWCASES = {'talentbridge': {'screenshots': [{'image': 'img/projects/talentbridge/01-dashboard.png',
                                   'alt': 'TalentBridge dashboard with demo data',
                                   'caption': 'Dashboard — synthetic demo data.',
                                   'width': 1440,
                                   'height': 1000},
                                  {'image': 'img/projects/talentbridge/02-candidates.png',
                                   'alt': 'TalentBridge candidates with demo data',
                                   'caption': 'Candidates — synthetic demo data.',
                                   'width': 1440,
                                   'height': 1100},
                                  {'image': 'img/projects/talentbridge/03-candidate-form.png',
                                   'alt': 'TalentBridge candidate form with demo data',
                                   'caption': 'Candidate form — synthetic demo data.',
                                   'width': 1440,
                                   'height': 1100},
                                  {'image': 'img/projects/talentbridge/04-vacancies.png',
                                   'alt': 'TalentBridge vacancies with demo data',
                                   'caption': 'Vacancies — synthetic demo data.',
                                   'width': 1440,
                                   'height': 1100},
                                  {'image': 'img/projects/talentbridge/05-matching.png',
                                   'alt': 'TalentBridge matching with demo data',
                                   'caption': 'Matching — synthetic demo data.',
                                   'width': 1440,
                                   'height': 1100},
                                  {'image': 'img/projects/talentbridge/06-interviews.png',
                                   'alt': 'TalentBridge interviews with demo data',
                                   'caption': 'Interviews — synthetic demo data.',
                                   'width': 1440,
                                   'height': 1100}],
                  'video': 'video/talentbridge-showcase.mp4',
                  'poster': 'img/projects/talentbridge/01-dashboard.png'},
 'smart-document-vault': {'screenshots': [{'image': 'img/projects/smart-document-vault/01-dashboard-light.png',
                                           'alt': 'Smart Document Vault dashboard light with demo '
                                                  'data',
                                           'caption': 'Dashboard light — synthetic demo data.',
                                           'width': 1440,
                                           'height': 1000},
                                          {'image': 'img/projects/smart-document-vault/02-dashboard-dark.png',
                                           'alt': 'Smart Document Vault dashboard dark with demo '
                                                  'data',
                                           'caption': 'Dashboard dark — synthetic demo data.',
                                           'width': 1440,
                                           'height': 1000},
                                          {'image': 'img/projects/smart-document-vault/03-security.png',
                                           'alt': 'Smart Document Vault security with demo data',
                                           'caption': 'Security — synthetic demo data.',
                                           'width': 1440,
                                           'height': 1000},
                                          {'image': 'img/projects/smart-document-vault/04-mobile-dashboard.png',
                                           'alt': 'Smart Document Vault mobile dashboard with demo '
                                                  'data',
                                           'caption': 'Mobile dashboard — synthetic demo data.',
                                           'width': 360,
                                           'height': 1000}],
                          'video': 'video/smart-document-vault-showcase.mp4',
                          'poster': 'img/projects/smart-document-vault/01-dashboard-light.png'}}
