# Generated by Django 4.2.5 on 2023-09-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=50)),
                ('short_desc', models.CharField(blank=True, max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('dob', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('is_available', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('last_degree', models.CharField(blank=True, max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
