# Generated by Django 4.2.5 on 2023-09-11 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_personalinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='desc',
            new_name='bio',
        ),
        migrations.RenameField(
            model_name='personalinfo',
            old_name='short_desc',
            new_name='short_bio',
        ),
    ]
