# Generated by Django 4.2.5 on 2023-09-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_desc_personalinfo_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
