# Generated by Django 4.2.5 on 2023-09-12 02:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_skill_value_skill_max_value_skill_min_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='min_value',
        ),
        migrations.AddField(
            model_name='skill',
            name='value',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
