# Generated by Django 4.2.5 on 2023-09-12 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_skill_max_value_remove_skill_min_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_name', models.CharField(max_length=50)),
                ('icon_color', models.CharField(max_length=7)),
            ],
        ),
    ]
