# Generated by Django 4.2.5 on 2023-09-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happy_client', models.PositiveIntegerField()),
                ('project', models.PositiveIntegerField()),
                ('support', models.PositiveIntegerField()),
                ('awards', models.PositiveIntegerField()),
            ],
        ),
    ]
