# Generated by Django 4.2.5 on 2023-09-12 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_company_name_experience_designation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='institute',
            new_name='company',
        ),
    ]
