# Generated by Django 4.2.5 on 2023-09-12 06:30

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rename_institute_experience_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
