# Generated by Django 4.2.5 on 2023-09-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='end_year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='education',
            name='start_year',
            field=models.CharField(max_length=10),
        ),
    ]
