# Generated by Django 4.2.5 on 2026-09-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_project_options_alter_projectimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contribution',
            field=models.TextField(blank=True, help_text='Describe your own responsibilities, not the whole team’s work.'),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons',
            field=models.TextField(blank=True, help_text='What did you learn or what would you improve next?'),
        ),
        migrations.AddField(
            model_name='project',
            name='outcome',
            field=models.TextField(blank=True, help_text='Describe delivered capabilities. Include metrics only when verified.'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, help_text='Who needed this and what problem did it address?'),
        ),
        migrations.AddField(
            model_name='project',
            name='technical_decisions',
            field=models.TextField(blank=True, help_text='Explain implementation choices and tradeoffs. One decision per paragraph.'),
        ),
    ]
