# Generated by Django 4.2.5 on 2026-09-17

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def populate_project_slugs(apps, schema_editor):
    Project = apps.get_model('home', 'Project')
    database = schema_editor.connection.alias
    used_slugs = set(
        Project.objects.using(database).exclude(slug__isnull=True)
        .values_list('slug', flat=True)
    )
    for project in Project.objects.using(database).filter(slug__isnull=True).order_by('pk'):
        base_slug = slugify(project.name) or 'project'
        candidate = base_slug[:120]
        suffix = 2
        while candidate in used_slugs:
            suffix_text = f'-{suffix}'
            candidate = f'{base_slug[:120 - len(suffix_text)]}{suffix_text}'
            suffix += 1
        project.slug = candidate
        project.save(update_fields=['slug'])
        used_slugs.add(candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_feature_new_case_studies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['group', 'order', 'name', 'pk']},
        ),
        migrations.AddField(
            model_name='project',
            name='api_docs_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='architecture_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='kind',
            field=models.CharField(
                choices=[('screenshot', 'Screenshot'), ('architecture', 'Architecture diagram')],
                default='screenshot', max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='skill',
            name='group',
            field=models.CharField(default='Core', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='EngineeringChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('problem', models.TextField(blank=True)),
                ('approach', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('trade_offs', models.TextField(blank=True)),
                ('verification', models.TextField(blank=True, help_text='State only results that can be verified.')),
                ('source_url', models.URLField(blank=True, help_text='Optional source supporting the verification.')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engineering_challenges', to='home.project')),
            ],
            options={'ordering': ['order', 'pk']},
        ),
        migrations.CreateModel(
            name='ExperienceBullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bullets', to='home.experience')),
            ],
            options={'ordering': ['order', 'pk']},
        ),
        migrations.CreateModel(
            name='ProjectMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('explanation', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, help_text='Source or measurement documentation for this metric.')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='home.project')),
            ],
            options={'ordering': ['order', 'pk']},
        ),
        migrations.RunPython(populate_project_slugs, migrations.RunPython.noop),
    ]
