# Generated by Django 4.2.5 on 2026-09-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_superseded_case_study_challenges'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='collaboration',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='constraints',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='contribution_areas',
            field=models.TextField(blank=True, help_text='Enter one contribution area per line.'),
        ),
        migrations.AddField(
            model_name='project',
            name='development_status',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='project',
            name='project_role',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='project',
            name='validation',
            field=models.TextField(blank=True),
        ),
    ]
