# Generated by Django 6.1.1 on 2026-10-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0038_add_ilmora_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("title_bn", models.CharField(blank=True, max_length=180)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                ("summary", models.TextField()),
                ("summary_bn", models.TextField(blank=True)),
                (
                    "body",
                    models.TextField(
                        help_text="Plain text paragraphs; HTML is escaped."
                    ),
                ),
                ("body_bn", models.TextField(blank=True)),
                ("topic", models.CharField(max_length=80)),
                ("source_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-published_at", "-pk"],
            },
        ),
        migrations.AlterModelOptions(
            name="contact",
            options={"ordering": ["-created_at", "-pk"]},
        ),
        migrations.AddField(
            model_name="contact",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="notification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="status",
            field=models.CharField(
                choices=[
                    ("unread", "Unread"),
                    ("read", "Read"),
                    ("replied", "Replied"),
                ],
                default="unread",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.TextField(
                blank=True,
                help_text="One technology per line; defaults to source-backed tags when empty.",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="work_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("backend", "Backend"),
                    ("frontend", "Frontend"),
                    ("fullstack", "Full-stack"),
                ],
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="consent_to_publish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testimonial",
            name="is_published",
            field=models.BooleanField(default=False),
        ),
    ]
