const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const assert=require('assert');
const fs=require('fs');
const base=process.env.PORTFOLIO_TEST_URL || 'http://127.0.0.1:8097';
if(!['127.0.0.1','localhost'].includes(new URL(base).hostname)) throw new Error('Run against a localhost test database only.');
fs.mkdirSync('output/screenshots',{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,...(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH ? {executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH} : {})});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(base+'/projects/');await page.locator('#project-search').fill('Ilmora');await page.locator('#project-type').selectOption('frontend');await page.locator('#project-tech').selectOption('React');await page.getByRole('button',{name:'Apply filters'}).click();assert.equal(await page.locator('.project-card').count(),1);await page.screenshot({path:process.cwd()+'/output/screenshots/project-filter-desktop.png',fullPage:true});await page.locator('#project-search').fill('NoSuchProject');await page.getByRole('button',{name:'Apply filters'}).click();assert.equal(await page.locator('.project-card').count(),0);await page.locator('.catalog-controls').getByText('Reset',{exact:true}).click();assert((await page.locator('.project-card').count())>1);
await page.goto(base+'/work/ilmora-madrasha-management/');assert.equal(await page.locator('.screenshot-gallery img').count(),6);for(const img of await page.locator('.screenshot-gallery img').all()){await img.scrollIntoViewIfNeeded();await img.evaluate(el=>el.decode());}
await page.locator('.screenshot-gallery [data-lightbox]').first().click();assert(await page.locator('#image-lightbox').isVisible());const first=await page.locator('#lightbox-image').getAttribute('src');await page.keyboard.press('ArrowRight');assert.notEqual(await page.locator('#lightbox-image').getAttribute('src'),first);await page.screenshot({path:process.cwd()+'/output/screenshots/project-lightbox.png'});await page.keyboard.press('Escape');assert(!(await page.locator('#image-lightbox').isVisible()));assert(await page.locator('.screenshot-gallery [data-lightbox]').first().evaluate(el=>el===document.activeElement));await page.locator('video').scrollIntoViewIfNeeded();await page.locator('video').evaluate(video=>video.play());await page.waitForTimeout(1000);assert(await page.locator('video').evaluate(video=>video.currentTime>0));await page.locator('video').evaluate(video=>video.pause());await page.screenshot({path:process.cwd()+'/output/screenshots/ilmora-case-study.png',fullPage:true});
await page.goto(base+'/articles/');assert.equal(await page.locator('.article-card').count(),3);await page.getByRole('button',{name:'বাংলা ব্যবহার করুন'}).click();assert.equal(await page.locator('html').getAttribute('lang'),'bn');await page.locator('.article-card .text-link').first().click();assert.equal(await page.locator('html').getAttribute('lang'),'bn');await page.screenshot({path:process.cwd()+'/output/screenshots/article-bangla.png',fullPage:true});await page.getByRole('button',{name:'Use English'}).click();
await page.goto(base+'/experience/talentbridge/');assert(await page.getByText('Responsibilities and contributions',{exact:true}).isVisible());await page.goto(base+'/contact/');await page.locator('#id_name').fill('Browser check');await page.locator('#id_email').fill('not-valid');await page.locator('#id_subject').fill('Verification');await page.locator('#id_message').fill('Local test message');assert(await page.locator('#id_email').evaluate(el=>!el.checkValidity()));await page.locator('#id_email').fill('browser@example.com');await page.getByRole('button',{name:'Send message'}).click();await page.waitForURL(base+'/#contact');assert(await page.getByText('Your message was saved. Thank you!',{exact:true}).isVisible());
await page.setViewportSize({width:390,height:844});for(const url of ['/','/projects/','/articles/','/work/ilmora-madrasha-management/']){await page.goto(base+url);const sizes=await page.evaluate(()=>({body:document.documentElement.scrollWidth,screen:innerWidth}));assert(sizes.body<=sizes.screen,JSON.stringify({url,sizes}));}
await page.goto(base+'/projects/');await page.screenshot({path:process.cwd()+'/output/screenshots/project-library-mobile.png',fullPage:true});await page.getByRole('button',{name:'Toggle navigation'}).click();assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'true');await page.keyboard.press('Escape');assert.equal(await page.locator('.menu-toggle').getAttribute('aria-expanded'),'false');assert.deepEqual(errors,[]);console.log('PASS: combined filters/reset, 6 loaded screenshots, keyboard lightbox/focus, playable video, bilingual articles, experience detail, saved contact, mobile overflow/navigation, no JS errors.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
