server {
    listen 80;
    listen [::]:80;
    server_name rahidulislam.com www.rahidulislam.com;

    client_max_body_size 25M;

    location /static/ {
        alias /srv/rahidulislam/current/staticfiles/;
        access_log off;
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }

    location /media/ {
        alias /var/lib/rahidulislam/media/;
        expires 1h;
        add_header Cache-Control "public, no-transform";
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://unix:/run/rahidulislam/gunicorn.sock;
        proxy_connect_timeout 10s;
        proxy_read_timeout 65s;
    }
}
